name: Vite
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.0
        cache: 'yarn'
    - name: install packages
      run: yarn install --frozen-lockfile
    - name: build
      run: yarn build
    - name: upload dist
      uses: actions/upload-artifact@v4
      with: 
        name: dist
        path: dist/
        if-no-files-found: error
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.0
        cache: 'yarn'
    - name: install packages
      run: yarn install --frozen-lockfile
    - name: build
      run: yarn test
  deploy:
    name: deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: download dist
      uses: actions/download-artifact@v4
      with:
        name: dist
    - name: test dist
      run: ls
